# 토큰의 암호화 복호화를 위한 secret key로서 이후 HS256 알고리즘을 사용하기 위해, 256비트보다 커야한다.
# 알파벳은 한단어 당 8bit 이므로 32글자 이상이면 된다.
springboot:
  jwt:
    access-secret: DaeguGreenArtAcademyClass502ForJavaSpringBootaaaasdf
    refresh-secret: HelloWorldRefreshTokenCreateBySecretHaHaaasdfasdf
    header-scheme-name: Authorization
    token-type: Bearer
    redis-access-black-key: "A-AT-BLACK"
    redis-refresh-key: "A-RT"
#DB
spring:
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 250MB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://112.222.157.156:55/greenjobgo1
    username: root
    password: greendev1

#mybatis

mybatis:
  type-aliases-package: com.green.greenjobgo1
  mapper-locations: mapper/**/*.xml

#SWAGGER
springdoc:
  swagger-ui:
    path: /swagger.html
    operations-sorter: method

file:
  dir: /home/download
---

spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:mariadb://localhost:3306/greenjobgo1
    username: root
    password: green502
  data:
    redis:
      host: localhost:3306
      port: 8080
  sql:
    init:
      mode: always
      schema-locations: classpath:init/schema.sql
      data-locations: classpath:init/data.sql

---

#DB
spring:
  config:
    activate:
      on-profile: "prod"
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    jdbc-url: jdbc:mariadb://112.222.157.156:55/greenjobgo1
    username: root
    password: greendev1
  data:
    redis:
      host: 192.168.0.27
      port: 56
app:
  oauth2:
    authorized-redirect-uris:
      - http://112.222.157.156/oauth/redirect
cors:
  allowed-origins: http://112.222.157.156

file:
  dir: /home/download

server:
  port: 8080
